logfile: midas-dmp.log
loglevel: DEBUG
dbio:
   factory:  fsbased
about: 
   title: "MIDAS Authoring Services"
   describedBy: "http://localhost:9091/midas/docs"
   href: "http://localhost:9091/midas/"
services: 
   dmp: 
      about: 
         message:     "DMP Service is available"
         title:       "Data Management Plan (DMP) Authoring API"
         describedBy: "http://localhost:9091/docs/dmpsvc-elements.html"
         href:        "http://localhost:9091/midas/dmp"

      clients: 
          midas: 
             default_shoulder: mdm1
          default: 
             default_shoulder: mdm1

      dbio: 
         superusers:                [ "rlp3" ]
         allowed_project_shoulders: ["mdm0", "mdm1"]
         default_shoulder:          mdm1

      default_convention: mdm1
      conventions: 
         mdm1: 
            about: 
                title:       "Data Management Plan (DMP) Authoring API (mdm1 convention)"
                describedBy: "http://localhost:9091/docs/dmpsvc-elements.html"
                href:        "http://localhost:9091/midas/dmp/mdm1"
                version:     mdm1
   group:
     about:
       message: "Group API available"
       title: "Group Management API"
       href: "http://localhost:9091/midas/group"
       describedBy: "http://localhost:9091/docs/groupsvc-elements.html"
     dbio:
       superusers: [ "rlp3" ]
       allowed_group_shoulders: [ "grp0" ]
       default_shoulder: grp0
     default_convention: grp0
     conventions:
       grp0: {}

