name: integration
on:
  workflow_dispatch:
  push:
    branches: [integration]
jobs:
  testall:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Containers
        env:
          OAR_DOCKERHUB_CRED: ${{ secrets.OAR_DOCKERHUB_CRED }}
        run: |
          bash scripts/dhsetup.sh
          cd docker && bash ./dockbuild.sh

      - name: Build & Run Python Tests via Docker
        run: scripts/testall.docker python

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-artifacts
          path: python/build/test-artifacts/

